/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FiszkiRouteImport } from './routes/fiszki'
import { Route as PrawdaFalszRouteImport } from './routes/prawda-falsz'
import { Route as SortowanieRouteImport } from './routes/sortowanie'
import { Route as SprintRouteImport } from './routes/sprint'
import { Route as TabelkaRouteImport } from './routes/tabelka'
import { Route as WybierzRouteImport } from './routes/wybierz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiszkiRoute = FiszkiRouteImport.update({
  id: '/fiszki',
  path: '/fiszki',
  getParentRoute: () => rootRouteImport,
} as any)
const PrawdaFalszRoute = PrawdaFalszRouteImport.update({
  id: '/prawda-falsz',
  path: '/prawda-falsz',
  getParentRoute: () => rootRouteImport,
} as any)
const SortowanieRoute = SortowanieRouteImport.update({
  id: '/sortowanie',
  path: '/sortowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintRoute = SprintRouteImport.update({
  id: '/sprint',
  path: '/sprint',
  getParentRoute: () => rootRouteImport,
} as any)
const TabelkaRoute = TabelkaRouteImport.update({
  id: '/tabelka',
  path: '/tabelka',
  getParentRoute: () => rootRouteImport,
} as any)
const WybierzRoute = WybierzRouteImport.update({
  id: '/wybierz',
  path: '/wybierz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fiszki': typeof FiszkiRoute
  '/prawda-falsz': typeof PrawdaFalszRoute
  '/sortowanie': typeof SortowanieRoute
  '/sprint': typeof SprintRoute
  '/tabelka': typeof TabelkaRoute
  '/wybierz': typeof WybierzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fiszki': typeof FiszkiRoute
  '/prawda-falsz': typeof PrawdaFalszRoute
  '/sortowanie': typeof SortowanieRoute
  '/sprint': typeof SprintRoute
  '/tabelka': typeof TabelkaRoute
  '/wybierz': typeof WybierzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fiszki': typeof FiszkiRoute
  '/prawda-falsz': typeof PrawdaFalszRoute
  '/sortowanie': typeof SortowanieRoute
  '/sprint': typeof SprintRoute
  '/tabelka': typeof TabelkaRoute
  '/wybierz': typeof WybierzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fiszki'
    | '/prawda-falsz'
    | '/sortowanie'
    | '/sprint'
    | '/tabelka'
    | '/wybierz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fiszki'
    | '/prawda-falsz'
    | '/sortowanie'
    | '/sprint'
    | '/tabelka'
    | '/wybierz'
  id:
    | '__root__'
    | '/'
    | '/fiszki'
    | '/prawda-falsz'
    | '/sortowanie'
    | '/sprint'
    | '/tabelka'
    | '/wybierz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FiszkiRoute: typeof FiszkiRoute
  PrawdaFalszRoute: typeof PrawdaFalszRoute
  SortowanieRoute: typeof SortowanieRoute
  SprintRoute: typeof SprintRoute
  TabelkaRoute: typeof TabelkaRoute
  WybierzRoute: typeof WybierzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiszki': {
      id: '/fiszki'
      path: '/fiszki'
      fullPath: '/fiszki'
      preLoaderRoute: typeof FiszkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prawda-falsz': {
      id: '/prawda-falsz'
      path: '/prawda-falsz'
      fullPath: '/prawda-falsz'
      preLoaderRoute: typeof PrawdaFalszRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sortowanie': {
      id: '/sortowanie'
      path: '/sortowanie'
      fullPath: '/sortowanie'
      preLoaderRoute: typeof SortowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint': {
      id: '/sprint'
      path: '/sprint'
      fullPath: '/sprint'
      preLoaderRoute: typeof SprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabelka': {
      id: '/tabelka'
      path: '/tabelka'
      fullPath: '/tabelka'
      preLoaderRoute: typeof TabelkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wybierz': {
      id: '/wybierz'
      path: '/wybierz'
      fullPath: '/wybierz'
      preLoaderRoute: typeof WybierzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FiszkiRoute: FiszkiRoute,
  PrawdaFalszRoute: PrawdaFalszRoute,
  SortowanieRoute: SortowanieRoute,
  SprintRoute: SprintRoute,
  TabelkaRoute: TabelkaRoute,
  WybierzRoute: WybierzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
